title: GitHub .vs. Bamboo .vs. Jenkins
author: Steven Kuhlmann
email: Steven.Kuhlmann@nov.com
description: > # this means to ignore newlines until "baseurl:"
  Comparing GitHub, Bamboo and Jenkins. Pros and Cons of using
  different Continuous Integration (CI)/ Continuous Delivery (CD)
  systems.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
